package windows

// Domain Functionnality Level
// Src:
const (
	DOMAIN_FUNCTIONNALITY_LEVEL_2000         = 0
	DOMAIN_FUNCTIONNALITY_LEVEL_2003_INTERIM = 1
	DOMAIN_FUNCTIONNALITY_LEVEL_2003         = 2
	DOMAIN_FUNCTIONNALITY_LEVEL_2008         = 3
	DOMAIN_FUNCTIONNALITY_LEVEL_2008_R2      = 4
	DOMAIN_FUNCTIONNALITY_LEVEL_2012         = 5
	DOMAIN_FUNCTIONNALITY_LEVEL_2012_R2      = 6
	DOMAIN_FUNCTIONNALITY_LEVEL_2016         = 7
)
